shin-lab-sec/cypas-cms

frontend/prisma/seed.ts
- seedが雑だったので、サンプルのコース・カリキュラムを生成できるようにした
=> seedにサンプルのデータを入れる

frontend/package.json, frontend/src/features/course/components/CourseForm.tsx, frontend/src/features/curriculum/components/CurriculumForm.tsx, frontend/src/features/curriculum/components/DraggableCurriculums.tsx, frontend/src/features/userAgent/components/UserAgentForm.tsx, frontend/src/pages/courses/index.tsx, frontend/src/pages/curriculums.tsx, frontend/src/pages/useragents.tsx, frontend/yarn.lock
- tabler-icons-reactを@tabler/react-iconsに置き換える
=> fix: tabler-icons-reactを@tabler/icons-reactに置き換える

docker-compose.yml, frontend/Dockerfile
- コンテナを立ち上げる時に、以下のコマンドも実行する
- yarn prisma migrate dev
- yarn install
=> feat: Nextjsの立ち上げ時に migrate, yarn iをする

README.md, frontend/.env, frontend/.env.sample, frontend/.gitignore
- .envファイルに書いているのが、開発ようの物なので .gitignoreから除く
- READMEを修正
=> feat: .envファイルをgitignoreしない

frontend/package.json, frontend/src/libs/cors.ts, frontend/src/pages/api/v1/articles/[id].ts, frontend/src/pages/api/v1/articles/index.ts, frontend/src/pages/api/v1/courses/[id].ts, frontend/src/pages/api/v1/courses/index.ts, frontend/src/pages/api/v1/sections/[id].ts, frontend/src/pages/api/v1/sections/index.ts, frontend/src/pages/api/v1/useragents/index.ts, frontend/yarn.lock
- cors設定の参考を作成した(https://cypas.sec)
- useragentsのapiのみだが、動作確認は済んでいる
- v1配下の全てのhandlerに対して設定を追加する必要がある
- Next.jsの公式[example](https://github.com/vercel/next.js/tree/canary/examples/api-routes-cors)
cypas-appを起動して、ブラウザからfetchできている様子
=> cors設定の参考を作成

frontend/prisma/migrations/20230630142910_add_ondelete/migration.sql, frontend/prisma/schema.prisma
- Article, Quizのスキーマに onDelete: Cascadeを追加する
- これで関連するSectionを消したとき、自身も消える
=> feat: Sectionを消したとき、関連するArticle, Quizを消す

frontend/src/pages/api/v1/articles/[id].ts, frontend/src/pages/api/v1/articles/index.ts
=> feat: api/v1/articles作成

frontend/.eslintrc.json, frontend/.husky/commit-msg, frontend/.husky/common.sh, frontend/.husky/pre-commit, frontend/.husky/pre-push, frontend/.lintstagedrc.json, frontend/commitlint.config.js, frontend/package.json, frontend/yarn.lock
husky, lintstaged, commitlintの導入
自動フォーマット追加
- コミット => pre-commit(husky) => lintstaged => eslint, prettierのチェックをする
- コミット => commit-msg(husky) => コミットメッセージのフォーマットをチェックする
- プッシュ => pre-push(husky) => 型チェックをする
ついで
- パッケージのprettier追加（IDEに頼りたくないから）
- eslint-plugin-prettier追加（prettier入れたことで、ESLintと競合するから）
- scriptsに、型チェック（type-check）追加
コミットメッセージ エラー
ESLint エラー
コミット成功
pushエラー
push成功
=> commit・pushでリンターをかける

frontend/src/features/article/ArticleEditor.tsx, frontend/src/features/article/Preview.tsx, frontend/src/features/section/components/DraggableSections.tsx, frontend/src/pages/courses/[courseId]/index.tsx
引数を持つ関数のPropsで、直接関数を渡す
```tsx
// before
return(
<SectionItem
key={index}
courseId={id}
section={section}
onUpdate={(id, v) => updateSection(id, v)}
onDelete={(sectionId: string) => deleteSection(sectionId)}
/>
)
// after
return(
<SectionItem
key={index}
courseId={id}
section={section}
onUpdate={updateSection}
onDelete={deleteSection}
/>
)
```
useStateのboolの箇所を、useBooleanで統一
=> 細かいリファクタリング

frontend/commitlint.config.js, frontend/src/features/course/components/CourseTable.tsx, frontend/src/features/course/hooks/useCourse.ts, frontend/src/features/section/components/DraggableSections.tsx, frontend/src/features/section/components/SectionItem.tsx, frontend/src/pages/api/courses/[id].ts, frontend/src/pages/api/courses/index.ts, frontend/src/pages/courses/index.tsx, frontend/src/types/schemaWithRelation.ts
- courses APIのレスポンスに必要ないincludesを削除する
- CourseWithSectionsの型を修正
- Course, SectionでいいのにwithRelationを使っている箇所を修正
- commitlintの feat: 以降の文字のルールを無効化
=> courses APIのレスポンスに必要ないincludesを削除する

frontend/prisma/migrations/20230909054337_y/migration.sql, frontend/prisma/schema.prisma
=> courseを消すとき、関連sectionも消す

frontend/src/pages/articles/[id].tsx
=> 記事ページでiframeに高さを渡す

frontend/src/features/course/components/CourseTable.tsx, frontend/src/features/course/hooks/useCourse.ts, frontend/src/features/section/components/DraggableSections.tsx, frontend/src/features/section/components/SectionItem.tsx, frontend/src/pages/api/courses/[id].ts, frontend/src/pages/api/courses/index.ts, frontend/src/pages/courses/[courseId]/[sectionId]/index.tsx, frontend/src/pages/courses/index.tsx, frontend/src/types/schemaWithRelation.ts
=> courseのAPIレスポンスにincludeも含め直す

frontend/src/features/article/Preview.tsx, frontend/src/features/section/components/DraggableSections.tsx
=> chore: ドラッグアンドドロップとPreviewでwindowReady消してもエラー出ないので消す

frontend/src/pages/articles/[id].tsx
[参考](https://zenn.dev/steelydylan/articles/embed-widget-js)
記事ページをiframeで呼び出す側へ送るメッセージの修正
- メッセージをそもそも送れなかったの
- 正しい画面のheightを送る（でも、urlのプレビュー表示とかあると、呼び出す側は更新する度に取得する高さ変わっちゃう、、）
呼び出す度に少し高さが変わっちゃう、、
=> articleを呼び出すiframeに正しいheightを送る

frontend/src/components/ImportFileInput.tsx, frontend/src/features/course/hooks/useCourse.ts, frontend/src/features/section/useSection.ts, frontend/src/pages/useragents.tsx
- ユーザーエージェントも、JSONファイルのインポートで作成出来るようにする
=> JSONファイルアップロードでユーザーエージェントを作成

frontend/src/components/ExportJsonButton.tsx, frontend/src/components/ImportFileInput.tsx
=> インポート・エクスポートボタンのスタイル変更

frontend/src/features/course/index.ts, frontend/src/features/course/useCourse.ts
- useCourseの階層移動
- コース画像選択inputで、画像だけ選択させる
=> useCourseの階層移動

frontend/src/features/article/Preview.tsx
=> zenn-content-cssを消していたので追加

frontend/src/features/course/components/CourseForm.tsx
=> コース画像のファイル選択で、画像のみ許可する

frontend/.env, frontend/src/middleware.ts, frontend/src/pages/api/auth.ts
- ベーシック認証の作成
- 全ページにベーシック認証を付ける
- .envファイルでユーザー名とパスワードを定義
=> ベーシック認証のAPI作成

frontend/src/features/article/ArticleEditor.tsx
=> feat: 記事のページ削除時に、確認アラート表示

frontend/src/components/Layout.tsx, frontend/src/features/article/ArticleEditor.tsx
=> いらないbackgroundを消す

frontend/src/middleware.ts
- 記事ページのBasic認証を外せ無いので、一旦全部のBasic認証を外す
=> delete: basic認証を外す
